"""database changes

Revision ID: 0da9deb9973c
Revises: a9b8c7d6e5f4
Create Date: 2026-06-23 17:28:11.335561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da9deb9973c'
down_revision: Union[str, Sequence[str], None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_variants_product_id_fkey'), 'product_variants', type_='foreignkey')
    op.create_foreign_key(None, 'product_variants', 'products', ['product_id'], ['product_id'])
    op.drop_constraint(op.f('restock_history_variant_id_fkey'), 'restock_history', type_='foreignkey')
    op.create_foreign_key(None, 'restock_history', 'product_variants', ['variant_id'], ['variant_id'])
    op.drop_constraint(op.f('sales_invoices_variant_id_fkey'), 'sales_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'sales_invoices', 'product_variants', ['variant_id'], ['variant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_invoices', type_='foreignkey')
    op.create_foreign_key(op.f('sales_invoices_variant_id_fkey'), 'sales_invoices', 'product_variants', ['variant_id'], ['variant_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'restock_history', type_='foreignkey')
    op.create_foreign_key(op.f('restock_history_variant_id_fkey'), 'restock_history', 'product_variants', ['variant_id'], ['variant_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.create_foreign_key(op.f('product_variants_product_id_fkey'), 'product_variants', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
