"""initial_migration

Revision ID: 82ec899019a5
Revises: abfb00a106cb
Create Date: 2026-06-18 16:20:03.885629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ec899019a5'
down_revision: Union[str, Sequence[str], None] = 'abfb00a106cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dateHired',
                existing_type=sa.VARCHAR(length=20),
                type_=sa.Date(),
                existing_nullable=True,
                postgresql_using='"dateHired"::date')  # Add this line
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dateHired',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
